name: Reusable Global Workflow

on:
  workflow_call:
    inputs:
      ambiente:
        required: true
        type: string

jobs:
  passos:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando o Reusable no repo3! Versão recebida -> ${{ inputs.ambiente }}"
